name: Unit Test / Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
